https://p2p.binance.com/bapi/c2c/v2/friendly/c2c/adv/search

// {
//     "fiat": "UAH",
//     "page": 1,
//     "rows": 10,
//     "tradeType": "BUY",
//     "asset": "USDT",
//     "countries": [],
//     "proMerchantAds": false,
//     "shieldMerchantAds": false,
//     "publisherType": null,
//     "payTypes": []
// }

// // POST Request axios

// // Response

// {
// 	"code": "000000",
// 	"message": null,
// 	"messageDetail": null,
// 	"data": [{
// 		"adv": {
// 			"advNo": "11509174866434076672",
// 			"classify": "mass",
// 			"tradeType": "SELL",
// 			"asset": "USDT",
// 			"fiatUnit": "UAH",
// 			"advStatus": null,
// 			"priceType": null,
// 			"priceFloatingRatio": null,
// 			"rateFloatingRatio": null,
// 			"currencyRate": null,
// 			"price": "37.55",
// 			"initAmount": null,
// 			"surplusAmount": "1378.43",
// 			"amountAfterEditing": null,
// 			"maxSingleTransAmount": "100000.00",
// 			"minSingleTransAmount": "2000.00",
// 			"buyerKycLimit": null,
// 			"buyerRegDaysLimit": null,
// 			"buyerBtcPositionLimit": null,
// 			"remarks": null,
// 			"autoReplyMsg": "",
// 			"payTimeLimit": 15,
// 			"tradeMethods": [{
// 				"payId": null,
// 				"payMethodId": "",
// 				"payType": null,
// 				"payAccount": null,
// 				"payBank": null,
// 				"paySubBank": null,
// 				"identifier": "Wise",
// 				"iconUrlColor": null,
// 				"tradeMethodName": "Wise",
// 				"tradeMethodShortName": null,
// 				"tradeMethodBgColor": "#00C6FF"
// 			}],
// 			"userTradeCountFilterTime": null,
// 			"userBuyTradeCountMin": null,
// 			"userBuyTradeCountMax": null,
// 			"userSellTradeCountMin": null,
// 			"userSellTradeCountMax": null,
// 			"userAllTradeCountMin": null,
// 			"userAllTradeCountMax": null,
// 			"userTradeCompleteRateFilterTime": null,
// 			"userTradeCompleteCountMin": null,
// 			"userTradeCompleteRateMin": null,
// 			"userTradeVolumeFilterTime": null,
// 			"userTradeType": null,
// 			"userTradeVolumeMin": null,
// 			"userTradeVolumeMax": null,
// 			"userTradeVolumeAsset": null,
// 			"createTime": null,
// 			"advUpdateTime": null,
// 			"fiatVo": null,
// 			"assetVo": null,
// 			"advVisibleRet": null,
// 			"assetLogo": null,
// 			"assetScale": 2,
// 			"fiatScale": 2,
// 			"priceScale": 2,
// 			"fiatSymbol": "₴",
// 			"isTradable": true,
// 			"dynamicMaxSingleTransAmount": "51708.33",
// 			"minSingleTransQuantity": "53.26",
// 			"maxSingleTransQuantity": "2663.11",
// 			"dynamicMaxSingleTransQuantity": "1377.05",
// 			"tradableQuantity": "1377.05",
// 			"commissionRate": "0.00100000",
// 			"tradeMethodCommissionRates": [],
// 			"launchCountry": null,
// 			"abnormalStatusList": null,
// 			"closeReason": null,
// 			"storeInformation": null
// 		},
// 		"advertiser": {
// 			"userNo": "s63f9677c42f53af38e73e5306eb1fa61",
// 			"realName": null,
// 			"nickName": "Speriter",
// 			"margin": null,
// 			"marginUnit": null,
// 			"orderCount": null,
// 			"monthOrderCount": 147,
// 			"monthFinishRate": 1.000,
// 			"positiveRate": 0.99333333,
// 			"advConfirmTime": null,
// 			"email": null,
// 			"registrationTime": null,
// 			"mobile": null,
// 			"userType": "user",
// 			"tagIconUrls": [],
// 			"userGrade": 2,
// 			"userIdentity": "",
// 			"proMerchant": null,
// 			"badges": null,
// 			"isBlocked": false,
// 			"activeTimeInSecond": 243
// 		}
// 	}]
// }

